### PR TITLE
Adds new -type and -uplink flags to register command

### PR DESCRIPTION
**Pull request by nkinkade**
This allows Autojoin clients to specify these v2.Registration fields and pass them to the Autojoin API as part of the registration process.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/autojoin/61)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autojoin/61)* status: 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`cmd/register/main.go` line 43 at r1](https://reviewable.io/reviews/m-lab/autojoin/61#-OCkP0w_A9FY8b5PooSy:-OCkP0w_A9FY8b5PooSz:b-c5wiu8) ([raw file](https://github.com/m-lab/autojoin/blob/59b8b0ea4ed7ec6b8c9185a83fb752068224decf/cmd/register/main.go#L43)):*
> ```Go
> 	ipv4        = flagx.StringFile{}
> 	ipv6        = flagx.StringFile{}
> 	machineType = flag.String("type", "", "The type of machine: physical or virtual")
> ```

Do you want these to be `flagx.StringFiles` also?

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autojoin/61)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/register/main.go` line 43 at r1](https://reviewable.io/reviews/m-lab/autojoin/61#-OCkP0w_A9FY8b5PooSy:-OCkPZCDAdYDUqDWlc2a:b-imcb2w) ([raw file](https://github.com/m-lab/autojoin/blob/59b8b0ea4ed7ec6b8c9185a83fb752068224decf/cmd/register/main.go#L43)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do you want these to be `flagx.StringFiles` also?
</blockquote></details>

I couldn't think of a use case. For M-Lab-managed VMs, there is no current metadata file that has anything about the fact that the machine is a VM, nor the uplink speed. For M-Lab-managed machines, for now only virtual machines will be using the Autojoin API, and it is easy enough to set the `-type` flag of the autonode-register container to "virtual". As far as the uplink speed, as far as I know the only way to understanding the uplink speed is to read the GCE documentation. I presume the same is true for other cloud providers. 

Are you imagining a case where those values would be written to a file by write-metadata.sh or similar and then read in by the register container?

**Review by stephen-soltesz — APPROVED** [review]
Thank you for this addition!!

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/autojoin/61#-:-OCkRmL241HoCrGzCZ-3:bars2af)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

___
*[`cmd/register/main.go` line 43 at r1](https://reviewable.io/reviews/m-lab/autojoin/61#-OCkP0w_A9FY8b5PooSy:-OCkRSjAEotE_FpVPfvn:bdq0fvn) ([raw file](https://github.com/m-lab/autojoin/blob/59b8b0ea4ed7ec6b8c9185a83fb752068224decf/cmd/register/main.go#L43)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I couldn't think of a use case. For M-Lab-managed VMs, there is no current metadata file that has anything about the fact that the machine is a VM, nor the uplink speed. For M-Lab-managed machines, for now only virtual machines will be using the Autojoin API, and it is easy enough to set the `-type` flag of the autonode-register container to "virtual". As far as the uplink speed, as far as I know the only way to understanding the uplink speed is to read the GCE documentation. I presume the same is true for other cloud providers. 

Are you imagining a case where those values would be written to a file by write-metadata.sh or similar and then read in by the register container?
</blockquote></details>

Thank you - I wasn't thinking through the specific cases. In the future, I could imagine if we want to use register for the physical nodes too. But, this doesn't need to be added now.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autojoin/61)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

___
*[`cmd/register/main.go` line 43 at r1](https://reviewable.io/reviews/m-lab/autojoin/61#-OCkP0w_A9FY8b5PooSy:-OCkS6Q56Vgb5kc2YzTR:bfepoch) ([raw file](https://github.com/m-lab/autojoin/blob/59b8b0ea4ed7ec6b8c9185a83fb752068224decf/cmd/register/main.go#L43)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you - I wasn't thinking through the specific cases. In the future, I could imagine if we want to use register for the physical nodes too. But, this doesn't need to be added now.
</blockquote></details>

I definitely have in mind investigating the use of Autojoin for physical machines too. Offloading DNS management from siteinfo seems desirable, and would be one less dependency on mlabconfig.py, which feels like another legacy piece of software that we rely on heavily today.

**Pull request merged**
